# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Inf2_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Informatyka_projekt2DialogBase(object):
    def setupUi(self, Informatyka_projekt2DialogBase):
        Informatyka_projekt2DialogBase.setObjectName("Informatyka_projekt2DialogBase")
        Informatyka_projekt2DialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(Informatyka_projekt2DialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")

        self.retranslateUi(Informatyka_projekt2DialogBase)
        self.button_box.accepted.connect(Informatyka_projekt2DialogBase.accept) # type: ignore
        self.button_box.rejected.connect(Informatyka_projekt2DialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Informatyka_projekt2DialogBase)

    def retranslateUi(self, Informatyka_projekt2DialogBase):
        _translate = QtCore.QCoreApplication.translate
        Informatyka_projekt2DialogBase.setWindowTitle(_translate("Informatyka_projekt2DialogBase", "Inf_proj2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Informatyka_projekt2DialogBase = QtWidgets.QDialog()
    ui = Ui_Informatyka_projekt2DialogBase()
    ui.setupUi(Informatyka_projekt2DialogBase)
    Informatyka_projekt2DialogBase.show()
    sys.exit(app.exec_())
